### ISSUE TITLE
Prepare for AWS Quick Starts

### ISSUE THREAD

**Issue by sbstjn** [superwerker/superwerker#91]
## Tasks

- [x] Logo
- [x] High Level Briefing
- [x] Documentation (_Deployment Guide_)
  - Website ( https://aws-quickstart.github.io/quickstart-dotnetcore-cicd/ ) 
  - PDF ( https://aws-quickstart.s3.amazonaws.com/quickstart-trek10-serverless-enterprise-cicd/doc/serverless-cicd-for-the-enterprise-on-the-aws-cloud.pdf ) 
- [x] Architecture Diagramm
- [x] Answer their questions so they can kick the project
- [x] Initial PR + pass review
- [x] Rename components to templates, rename yaml to template.yaml
- [x] Tag Customer Facing templates with correct metadata (see active directory quickstart)
- [x] Use Active Directory quickstart deployment guide as a gold standard example
- [x] Merge 1.0 fixes into Quickstarts Repo
- [x] Clarify how `TemplateUrlPrefix` and `SuperwerkerVersion` metadata are used in the quickstart context (_question already raised._)

## Commands

```bash
$ > ./docs/boilerplate/.utils/generate_dynamic_content.sh
$ > asciidoctor --base-dir docs/ --backend=html5 -o ../docs/index.html -w --doctype=book -a toc2 docs/boilerplate/index.adoc
```

## Topics

- What you'll build
- How to deploy
- Cost and licenses
- Resources

## Examples

- https://aws.amazon.com/quickstart/architecture/serverless-cicd-for-enterprise/
- https://aws.amazon.com/quickstart/architecture/eks-snyk/
- https://aws.amazon.com/quickstart/architecture/terraform-modules-on-aws/
- https://aws.amazon.com/quickstart/architecture/ibm-maximo/

**Comment by s0enke** [comment]
Quickstarts are no part of 1.0. Quickstarts depend on 1.0, but not the other way round.

**Comment by s0enke** [comment]
https://aws.amazon.com/quickstart/architecture/superwerker/
